# Empty listen_addresses to use systemd socket activation
listen_addresses = ['[::]:5300']
max_clients = 1024
timeout = 2000
keepalive = 1200
cert_refresh_delay = 90

server_names = ['doh.appliedprivacy.net', 'doh.ffmuc.net', 'doh.ffmuc.net-2', 'ffmuc.net', 'meganerd', 'meganerd-doh-ipv4', 'pf-doh', 'dns.watch', 'dns.digitale-gesellschaft.ch', 'dns.digitale-gesellschaft.ch-2', 'doh-ibksturm', 'ibksturm', 'libredns', 'bortzmeyer', 'circl-doh', 'scaleway-fr', 'scaleway-ams']
lb_strategy = 'p4' # dont go higher. otherwise latency becomes unacceptable on RPi1
#lb_strategy = 'random'
lb_estimator = false
dnscrypt_servers = true
doh_servers = true
ipv4_servers = true
ipv6_servers = true
block_ipv6 = false
block_unqualified = true
block_undelegated = true
require_nolog = true
require_nofilter = true
require_dnssec = true

cache = false
cache_size = 512
cache_min_ttl = 180
cache_max_ttl = 360
cache_neg_min_ttl = 240
cache_neg_max_ttl = 900

forwarding_rules = 'forwarding_rules.txt'

[query_log]
  #file = '/var/log/dnscrypt-proxy/query.log'
  #file = '/dev/stdout'
  file = '/dev/null'

[nx_log]
  #file = '/var/log/dnscrypt-proxy/nx.log'
  #file = '/dev/stdout'
  file = '/dev/null'

[sources]
  [sources.'public-resolvers']
  url = 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md'
  cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''

